let ALL=null;const app=document.getElementById("app"),MIN=3827001,MAX=3827100;
const stages=[["foundation","Foundation – KNOW","CBSE core mastery"],["logical","Logical – THINK","CBSE competency and application"],["elite","Elite – MASTER","CBSE core + controlled ICSE / IGCSE / IB MYP exposure"],["challenge","Master Challenge","CBSE mastery + selected international-style exposure"]];
const levels=["Number Mastery","Number Theory","Fractions & Decimals","Powers & Algebra","Algebra & Equations","Commercial Maths","Geometry","Mensuration","Data & Statistics","CBSE Excellence"];
fetch("questions.json").then(r=>r.json()).then(x=>{ALL=x.questions;load("student",0)?dashboard():home()}).catch(()=>app.innerHTML='<div class="wrap"><div class="card"><h2>Question bank failed to load</h2><p>Keep index.html, app.js, style.css and questions.json together in the same GitHub Pages folder.</p></div></div>');
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function home(){app.innerHTML=`<div class="wrap"><div class="hero"><h1>B.S. RAO GOLDEN 10™</h1><p>ONE PROGRAM • 200 TESTS • 4,000 ORIGINAL QUESTIONS</p></div><div class="card"><h2>Student Login</h2><p class="muted">Hall Ticket range: 3827001–3827100</p><input id="hall" inputmode="numeric" maxlength="7" placeholder="Enter Hall Ticket Number" style="padding:13px;width:100%;border:1px solid #ccd4e0;border-radius:10px"><br><br><button class="btn" onclick="login()">Login</button><p id="err" class="bad"></p></div><div class="card"><b>Question rotation:</b> the same student receives unused question IDs on each retake until that test's pool is exhausted.</div></div>`}
function login(){let h=Number(document.getElementById("hall").value);if(h>=MIN&&h<=MAX&&Number.isInteger(h)){save("student",h);dashboard()}else document.getElementById("err").textContent="Use a Hall Ticket from 3827001 to 3827100."}
function dashboard(){app.innerHTML=`<div class="wrap"><div class="top"><h1>Student Dashboard</h1><button class="btn alt" onclick="logout()">Logout</button></div><div class="card"><h2>Hall Ticket: ${load("student","")}</h2><div class="grid">${[6,7,8,9,10].map(c=>`<button class="btn level" onclick="levelsPage(${c})">CLASS ${c}<br><small>10 Golden Levels</small></button>`).join("")}</div></div><div class="card"><b>Stage philosophy:</b> Foundation = CBSE; Logical = CBSE competency; Elite/Master = CBSE-first with controlled international curriculum exposure.</div></div>`}
function levelsPage(c){app.innerHTML=`<div class="wrap"><div class="top"><h1>Class ${c}</h1><button class="btn alt" onclick="dashboard()">Dashboard</button></div><div class="card"><div class="grid">${levels.map((x,i)=>`<button class="btn alt level" onclick="stagePage(${c},${i+1})">LEVEL ${i+1}<br>${esc(x)}</button>`).join("")}</div></div></div>`}
function stagePage(c,l){app.innerHTML=`<div class="wrap"><div class="top"><h1>Class ${c} • Level ${l}</h1><button class="btn alt" onclick="levelsPage(${c})">Levels</button></div>${stages.map(s=>`<div class="card"><h2>${s[1]}</h2><p>${s[2]}</p><button class="btn" onclick="start(${c},${l},'${s[0]}')">Start Test</button></div>`).join("")}</div>`}
function start(c,l,s){let key=`${load("student",0)}|${c}|${l}|${s}`,used=load("used",{}),old=used[key]||[],pool=ALL.filter(q=>q.class===c&&q.level===l&&q.stage===s&&!old.includes(q.id));if(pool.length<20){old=[];pool=ALL.filter(q=>q.class===c&&q.level===l&&q.stage===s)}pool.sort(()=>Math.random()-.5);let qs=pool.slice(0,20);used[key]=old.concat(qs.map(q=>q.id));save("used",used);save("active",{c,l,s,qs,attempt:old.length/20+1});test()}
function test(){let t=load("active",null),i=0,ans={};function draw(){let q=t.qs[i];app.innerHTML=`<div class="wrap"><div class="top"><h2>Class ${t.c} • Level ${t.l}</h2><span>Attempt ${t.attempt} • Q ${i+1}/20</span></div><div class="barbg"><div class="bar" style="width:${i*5}%"></div></div><div class="card"><span class="pill">${esc(q.subject)}</span><span class="pill">${esc(q.style)}</span><span class="pill">${esc(q.chapter)}</span><p class="q"><b>${i+1}. ${esc(q.question)}</b></p>${q.options.map(o=>`<button class="opt ${ans[i]===o?"sel":""}" onclick="pick(${JSON.stringify(o)})">${esc(o)}</button>`).join("")}</div><div class="top"><button class="btn alt" onclick="prev()" ${i?"":"disabled"}>Previous</button><button class="btn" onclick="${i===19?"finish()":"next()"}">${i===19?"Submit":"Next"}</button></div></div>`}window.pick=o=>{ans[i]=o;draw()};window.next=()=>{if(i<19){i++;draw()}};window.prev=()=>{if(i){i--;draw()}};window.finish=()=>{let score=0;t.qs.forEach((q,n)=>{if(ans[n]===q.answer)score+=4;else if(ans[n])score-=1});save("result",{...t,ans,score});result()};draw()}
function result(){let r=load("result",null),correct=r.qs.filter((q,i)=>r.ans[i]===q.answer).length,attempted=Object.keys(r.ans).length;app.innerHTML=`<div class="wrap"><div class="card center"><h1>Test Result</h1><p>Class ${r.c} • Level ${r.l} • ${stages.find(x=>x[0]===r.s)[1]}</p><div class="score">${r.score}/80</div><p>Correct: ${correct} • Wrong: ${attempted-correct} • Unattempted: ${20-attempted}</p><button class="btn" onclick="start(${r.c},${r.l},'${r.s}')">Retake – New Questions</button> <button class="btn alt" onclick="stagePage(${r.c},${r.l})">Back</button></div><div class="card"><h3>Answer Review</h3>${r.qs.map((q,i)=>`<p><b>${i+1}.</b> ${esc(q.question)}<br>Your: ${esc(r.ans[i]||"Unattempted")} | Correct: ${esc(q.answer)}</p>`).join("")}</div></div>`}
function logout(){localStorage.removeItem("student");home()}
