let ALL=[];const app=document.getElementById("app"),MIN=3827001,MAX=3827100;
const stages=[["foundation","Foundation – KNOW","CBSE core mastery"],["logical","Logical – THINK","CBSE competency and application"],["elite","Elite – MASTER","CBSE-first with controlled international-style exposure"],["challenge","Master Challenge","CBSE mastery + selected international-style exposure"]];
const levels=["Number Mastery","Number Theory","Fractions & Decimals","Powers","Exponents & Algebra","Commercial Maths","Geometry","Mensuration","Advanced Foundation","CBSE Excellence"];
function esc(s){return String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
async function boot(){try{let r=await fetch("questions.json?ver=3",{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);let d=await r.json();ALL=Array.isArray(d.questions)?d.questions:[];if(ALL.length!==12000)throw Error("Verified bank size mismatch");}catch(e){app.innerHTML=`<div class="wrap"><div class="card"><h2>Verified question bank not ready</h2><p>${esc(e.message)}</p><p>For academic integrity, this version will not substitute generic questions.</p></div></div>`;return}load("student",0)?dashboard():home()}
function home(){app.innerHTML=`<div class="wrap"><div class="hero"><h1>B.S. RAO GOLDEN 10™</h1><p>200 TESTS • 12,000 VERIFIED-STRUCTURE QUESTIONS</p></div><div class="card"><h2>Student Login</h2><p class="muted">Hall Ticket range: 3827001–3827100</p><input id="hall" inputmode="numeric" maxlength="7" placeholder="Enter Hall Ticket Number" style="padding:13px;width:100%;border:1px solid #ccd4e0;border-radius:10px"><br><br><button class="btn" onclick="login()">Login</button><p id="err" class="bad"></p></div><div class="card"><b>Retake rotation:</b> unused question IDs are used first; after the 60-question pool is exhausted, the pool can recycle.</div></div>`}
function login(){let h=Number(document.getElementById("hall").value);if(Number.isInteger(h)&&h>=MIN&&h<=MAX){save("student",h);dashboard()}else document.getElementById("err").textContent="Use Hall Ticket 3827001–3827100."}
function dashboard(){app.innerHTML=`<div class="wrap"><div class="top"><h1>Student Dashboard</h1><button class="btn alt" onclick="logout()">Logout</button></div><div class="card"><h2>Hall Ticket: ${load("student","")}</h2><div class="grid">${[6,7,8,9,10].map(c=>`<button class="btn level" onclick="levelsPage(${c})">CLASS ${c}<br><small>10 Golden Levels</small></button>`).join("")}</div></div><div class="card"><b>Stage philosophy:</b> Foundation = CBSE core; Logical = competency; Elite/Master = CBSE-first with controlled international-style presentation and reasoning.</div></div>`}
function levelsPage(c){app.innerHTML=`<div class="wrap"><div class="top"><h1>Class ${c}</h1><button class="btn alt" onclick="dashboard()">Dashboard</button></div><div class="card"><div class="grid">${levels.map((x,i)=>`<button class="btn alt level" onclick="stagePage(${c},${i+1})">LEVEL ${i+1}<br>${esc(x)}</button>`).join("")}</div></div></div>`}
function stagePage(c,l){app.innerHTML=`<div class="wrap"><div class="top"><h1>Class ${c} • Level ${l}</h1><button class="btn alt" onclick="levelsPage(${c})">Levels</button></div>${stages.map(s=>`<div class="card"><h2>${s[1]}</h2><p>${s[2]}</p><button class="btn" onclick="startTest(${c},${l},'${s[0]}')">Start Test</button></div>`).join("")}</div>`}
function startTest(c,l,s){let student=load("student",0),key=`${student}|${c}|${l}|${s}`,used=load("usedQuestions",{}),old=used[key]||[],pool=ALL.filter(q=>q.class===c&&q.level===l&&q.stage===s&&!old.includes(q.id));if(pool.length<20){old=[];pool=ALL.filter(q=>q.class===c&&q.level===l&&q.stage===s)}if(pool.length<20){alert("This test pool is incomplete. Please contact the academy.");return}let by={};pool.forEach(q=>(by[q.subject]??=[]).push(q));let need=c<10?{Mathematics:10,Science:10}:{Mathematics:10,Physics:5,Chemistry:5};let qs=[];for(const [sub,n] of Object.entries(need)){let a=(by[sub]||[]).sort(()=>Math.random()-.5).slice(0,n);if(a.length<n){alert("Subject balance error. Test not started.");return}qs.push(...a)}qs.sort(()=>Math.random()-.5);used[key]=old.concat(qs.map(q=>q.id));save("usedQuestions",used);save("activeTest",{c,l,s,qs,attempt:Math.floor(old.length/20)+1});testPage()}
function testPage(){const t=load("activeTest",null);if(!t)return dashboard();let i=0,answers={};function draw(){let q=t.qs[i];app.innerHTML=`<div class="wrap"><div class="top"><h2>Class ${t.c} • Level ${t.l}</h2><span>Attempt ${t.attempt} • Q ${i+1}/20</span></div><div class="card"><span class="pill">${esc(q.subject)}</span><span class="pill">${esc(q.style)}</span><span class="pill">${esc(q.chapter)}</span><p class="q"><b>${i+1}. ${esc(q.question)}</b></p>${q.options.map(o=>`<button class="opt ${answers[i]===o?"sel":""}" onclick="choose(${JSON.stringify(o)})">${esc(o)}</button>`).join("")}</div><div class="top"><button class="btn alt" onclick="prevQ()" ${i?"":"disabled"}>Previous</button><button class="btn" onclick="${i===19?"submitTest()":"nextQ()"}">${i===19?"Submit":"Next"}</button></div></div>`}window.choose=o=>{answers[i]=o;draw()};window.nextQ=()=>{if(i<19){i++;draw()}};window.prevQ=()=>{if(i>0){i--;draw()}};window.submitTest=()=>{let score=0;t.qs.forEach((q,n)=>{if(answers[n]===q.answer)score+=4;else if(answers[n])score-=1});save("lastResult",{...t,answers,score});resultPage()};draw()}
function resultPage(){let r=load("lastResult",null);if(!r)return dashboard();let correct=r.qs.filter((q,i)=>r.answers[i]===q.answer).length,attempted=Object.keys(r.answers).length;app.innerHTML=`<div class="wrap"><div class="card center"><h1>Test Result</h1><p>Class ${r.c} • Level ${r.l} • ${stages.find(x=>x[0]===r.s)[1]}</p><div class="score">${r.score}/80</div><p>Correct: ${correct} • Wrong: ${attempted-correct} • Unattempted: ${20-attempted}</p><button class="btn" onclick="startTest(${r.c},${r.l},'${r.s}')">Retake – New Questions</button><button class="btn alt" onclick="stagePage(${r.c},${r.l})">Back</button></div><div class="card"><h3>Answer Review</h3>${r.qs.map((q,i)=>`<p><b>${i+1}.</b> ${esc(q.question)}<br>Your: ${esc(r.answers[i]||"Unattempted")} | Correct: ${esc(q.answer)}<br><span class="muted">${esc(q.explanation||"")}</span></p>`).join("")}</div></div>`}
function logout(){localStorage.removeItem("student");home()}boot();